### ISSUE TITLE
Docs: how long does the link last?

### ISSUE THREAD

**Issue by shipurjan** [gillchristian/tsplay.dev#127]
I want to know how long do the links last?
Are they deleted after some time?
I can't find it in the README or on the website.
I wanted to include those links in codebase comments, but if they're going to expire then I can't.

**Comment by gillchristian** [comment]
At the moment links aren't automatically deleted.

I've cleaned up 1 off links a few times (links created a few months prior that 0 or 1 visits). I might automate that in the future. But if a link was visited I won't deleted it.

To answer your question, it should be safe to use the links on codebase comments. As long as I maintain the service, at least.

**Comment by shipurjan** [comment]
Okay thanks 👍
