### ISSUE TITLE
Inconsistent creation of custom back half links

### ISSUE THREAD

**Issue by cursorsdottsx** [gillchristian/tsplay.dev#85]
Sorry I’m creating this on mobile.

This is definitely an excellent tool but I find that I cannot create short links using playground links that contain anything else other then #code. Ex I include target or another tsconfig option and it says Opps something went wrong. It would be better if it could be more specific about the problem. Thanks.

**Comment by gillchristian** [comment]
Thanks for reporting.

Could you provide some examples of the URLs that fail?

Also, this is unrelated, but doesn't it happen in the website or the playground plugin?

**Comment by cursorsdottsx** [comment]
I was just trying out custom back half links like lcsdiff and such. It didn’t work the first few times so I removed target from the link and it created it successfully. Then I came back with another with the name rustdiff1 without the target included in the link and it didn’t work. Going to these links redirects to home page so that means they aren’t taken.

**Comment by gillchristian** [comment]
Ohh yeah currently it will not let you create duplicated links, I think I should remove that

**Comment by gillchristian** [comment]
It should support creating several short links for the same link now
