### ISSUE TITLE
feat: Chrome plugin to short url at https://www.typescriptlang.org/play directly

### ISSUE THREAD

**Issue by JounQin** [gillchristian/tsplay.dev#97]

**Comment by gillchristian** [comment]
Great idea! I don't think I'll have time soon to work on this though :grimacing:

**Comment by gillchristian** [comment]
Btw, there's a plugin to generate short links directly from the playground.

Install with this link: https://www.typescriptlang.org/play?install-plugin=typescript-playground-link-shortener
